##==============================================================================
## Excavator
##
## @description: Makefile for Excavator.java
## @author: Elisha Lai
## @version: 1.0 25/10/2015
##==============================================================================

all:
	@echo "Compiling..."
	javac *.java

run: all
	@echo "Running..."
	java Excavator

.PHONY: clean

clean:
	@echo "Cleaning..."
	find . -name "*.class" -delete
